//
//  StyleKitName.h
//  Помощник риэлтора
//
//  Created by Michael Kozlyukov on 20.03.17.
//  Copyright © 2017 Chebahatt. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef enum : NSInteger
{
    StyleKitNameResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    StyleKitNameResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    StyleKitNameResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    StyleKitNameResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} StyleKitNameResizingBehavior;

extern CGRect StyleKitNameResizingBehaviorApply(StyleKitNameResizingBehavior behavior, CGRect rect, CGRect target);


@interface StyleKitName : NSObject

// Colors
+ (UIColor*)gradientColor;
+ (UIColor*)gradientColor2;
+ (UIColor*)gradientColor5;
+ (UIColor*)gradientColor6;
+ (UIColor*)color;
+ (UIColor*)textForeground;

// Gradients
+ (CGGradientRef)backgroundColor;
+ (CGGradientRef)tabBar;

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas1WithFrame: (CGRect)targetFrame resizing: (StyleKitNameResizingBehavior)resizing;

@end
