//
//  StyleKitName.m
//  Помощник риэлтора
//
//  Created by Michael Kozlyukov on 20.03.17.
//  Copyright © 2017 Chebahatt. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Cache

static UIColor* _gradientColor = nil;
static UIColor* _gradientColor2 = nil;
static UIColor* _gradientColor5 = nil;
static UIColor* _gradientColor6 = nil;
static UIColor* _color = nil;
static UIColor* _textForeground = nil;

static CGGradientRef _backgroundColor = NULL;
static CGGradientRef _tabBar = NULL;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _gradientColor = [UIColor colorWithRed: 0 green: 0.918 blue: 0.973 alpha: 1];
    _gradientColor2 = [UIColor colorWithRed: 0.427 green: 0.259 blue: 0.937 alpha: 1];
    _gradientColor5 = [UIColor colorWithRed: 0.78 green: 0.906 blue: 0.922 alpha: 0.299];
    _gradientColor6 = [UIColor colorWithRed: 0.624 green: 0.984 blue: 0.961 alpha: 0.5];
    _color = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];
    _textForeground = [UIColor colorWithRed: 0.169 green: 0.827 blue: 0.859 alpha: 1];

    // Gradients Initialization
    CGFloat backgroundColorLocations[] = {0, 1};
    _backgroundColor = CGGradientCreateWithColors(NULL, (__bridge CFArrayRef)@[(id)StyleKitName.gradientColor.CGColor, (id)StyleKitName.gradientColor2.CGColor], backgroundColorLocations);
    CGFloat tabBarLocations[] = {0, 1};
    _tabBar = CGGradientCreateWithColors(NULL, (__bridge CFArrayRef)@[(id)StyleKitName.gradientColor5.CGColor, (id)StyleKitName.gradientColor6.CGColor], tabBarLocations);

}

#pragma mark Colors

+ (UIColor*)gradientColor { return _gradientColor; }
+ (UIColor*)gradientColor2 { return _gradientColor2; }
+ (UIColor*)gradientColor5 { return _gradientColor5; }
+ (UIColor*)gradientColor6 { return _gradientColor6; }
+ (UIColor*)color { return _color; }
+ (UIColor*)textForeground { return _textForeground; }

#pragma mark Gradients

+ (CGGradientRef)backgroundColor { return _backgroundColor; }
+ (CGGradientRef)tabBar { return _tabBar; }

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
    [StyleKitName drawCanvas1WithFrame: CGRectMake(0, 0, 375, 667) resizing: StyleKitNameResizingBehaviorStretch];
}

+ (void)drawCanvas1WithFrame: (CGRect)targetFrame resizing: (StyleKitNameResizingBehavior)resizing
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //// Resize to Target Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = StyleKitNameResizingBehaviorApply(resizing, CGRectMake(0, 0, 375, 667), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 375, resizedFrame.size.height / 667);


    //// Color Declarations
    UIColor* fillColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* gradientColor3 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 0.5];
    UIColor* gradientColor4 = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 0.5];
    UIColor* fillColor2 = [UIColor colorWithRed: 0.012 green: 0.584 blue: 0.992 alpha: 1];
    UIColor* strokeColor = [UIColor colorWithRed: 0.329 green: 0.78 blue: 0.988 alpha: 1];
    UIColor* strokeColor2 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color3 = [UIColor colorWithRed: 0.714 green: 0.983 blue: 0.934 alpha: 1];

    //// Gradient Declarations
    CGFloat linearGradientLocations[] = {0, 1};
    CGGradientRef linearGradient = CGGradientCreateWithColors(NULL, (__bridge CFArrayRef)@[(id)gradientColor3.CGColor, (id)gradientColor4.CGColor], linearGradientLocations);

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 20, 375, 647)];
    CGContextSaveGState(context);
    [rectanglePath addClip];
    CGContextDrawLinearGradient(context, StyleKitName.backgroundColor, CGPointMake(187.5, 20), CGPointMake(187.5, 667), kNilOptions);
    CGContextRestoreGState(context);


    //// Page-
    {
        //// Group Начальный-экран
        {
            //// Defeault-screen 2
            {
                //// Group 3
                {
                    //// PlusButton
                    {
                        //// Oval
                        {
                            //// path- 3 Drawing
                            UIBezierPath* path3Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(163, 33, 50, 50)];
                            [fillColor2 setFill];
                            [path3Path fill];


                            //// path- 4 Drawing
                            UIBezierPath* path4Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(163, 33, 50, 50)];
                            CGContextSaveGState(context);
                            [path4Path addClip];
                            CGContextDrawLinearGradient(context, linearGradient,
                                CGPointMake(188, 51.83),
                                CGPointMake(188, 83),
                                kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
                            CGContextRestoreGState(context);
                            [strokeColor setStroke];
                            path4Path.lineWidth = 1;
                            [path4Path stroke];
                        }


                        //// Path 5 Drawing
                        UIBezierPath* path5Path = [UIBezierPath bezierPath];
                        [path5Path moveToPoint: CGPointMake(191.34, 54.51)];
                        [path5Path addLineToPoint: CGPointMake(200.5, 54.51)];
                        [path5Path addLineToPoint: CGPointMake(200.5, 61.49)];
                        [path5Path addLineToPoint: CGPointMake(191.34, 61.49)];
                        [path5Path addLineToPoint: CGPointMake(191.34, 71.96)];
                        [path5Path addLineToPoint: CGPointMake(185.23, 71.96)];
                        [path5Path addLineToPoint: CGPointMake(185.23, 61.49)];
                        [path5Path addLineToPoint: CGPointMake(176.07, 61.49)];
                        [path5Path addLineToPoint: CGPointMake(176.07, 54.51)];
                        [path5Path addLineToPoint: CGPointMake(185.23, 54.51)];
                        [path5Path addLineToPoint: CGPointMake(185.23, 44.04)];
                        [path5Path addLineToPoint: CGPointMake(191.34, 44.04)];
                        [path5Path addLineToPoint: CGPointMake(191.34, 54.51)];
                        [path5Path closePath];
                        path5Path.usesEvenOddFillRule = YES;
                        [fillColor setFill];
                        [path5Path fill];
                        [strokeColor2 setStroke];
                        path5Path.lineWidth = 1;
                        path5Path.miterLimit = 4;
                        [path5Path stroke];
                    }
                }
            }
        }
    }


    //// Page- 2
    {
        //// Group Начальный-экран 2
        {
            //// Defeault-screen 3
            {
                //// SettingsButton Drawing
                UIBezierPath* settingsButtonPath = [UIBezierPath bezierPath];
                [settingsButtonPath moveToPoint: CGPointMake(336, 63)];
                [settingsButtonPath addCurveToPoint: CGPointMake(331, 58) controlPoint1: CGPointMake(333.24, 63) controlPoint2: CGPointMake(331, 60.76)];
                [settingsButtonPath addCurveToPoint: CGPointMake(336, 53) controlPoint1: CGPointMake(331, 55.24) controlPoint2: CGPointMake(333.24, 53)];
                [settingsButtonPath addCurveToPoint: CGPointMake(341, 58) controlPoint1: CGPointMake(338.76, 53) controlPoint2: CGPointMake(341, 55.24)];
                [settingsButtonPath addCurveToPoint: CGPointMake(336, 63) controlPoint1: CGPointMake(341, 60.76) controlPoint2: CGPointMake(338.76, 63)];
                [settingsButtonPath addLineToPoint: CGPointMake(336, 63)];
                [settingsButtonPath closePath];
                [settingsButtonPath moveToPoint: CGPointMake(336, 48)];
                [settingsButtonPath addCurveToPoint: CGPointMake(326, 58) controlPoint1: CGPointMake(330.48, 48) controlPoint2: CGPointMake(326, 52.48)];
                [settingsButtonPath addCurveToPoint: CGPointMake(336, 68) controlPoint1: CGPointMake(326, 63.52) controlPoint2: CGPointMake(330.48, 68)];
                [settingsButtonPath addCurveToPoint: CGPointMake(346, 58) controlPoint1: CGPointMake(341.52, 68) controlPoint2: CGPointMake(346, 63.52)];
                [settingsButtonPath addCurveToPoint: CGPointMake(336, 48) controlPoint1: CGPointMake(346, 52.48) controlPoint2: CGPointMake(341.52, 48)];
                [settingsButtonPath addLineToPoint: CGPointMake(336, 48)];
                [settingsButtonPath closePath];
                [settingsButtonPath moveToPoint: CGPointMake(354.13, 65.61)];
                [settingsButtonPath addCurveToPoint: CGPointMake(346.85, 68.59) controlPoint1: CGPointMake(349.65, 67.44) controlPoint2: CGPointMake(349.63, 67.45)];
                [settingsButtonPath addCurveToPoint: CGPointMake(343.55, 76.45) controlPoint1: CGPointMake(345.79, 71.11) controlPoint2: CGPointMake(346.65, 69.06)];
                [settingsButtonPath addCurveToPoint: CGPointMake(335.68, 73.16) controlPoint1: CGPointMake(337.07, 73.74) controlPoint2: CGPointMake(338.62, 74.39)];
                [settingsButtonPath addCurveToPoint: CGPointMake(328.39, 76.14) controlPoint1: CGPointMake(333.17, 74.18) controlPoint2: CGPointMake(334.83, 73.5)];
                [settingsButtonPath addCurveToPoint: CGPointMake(325.41, 68.85) controlPoint1: CGPointMake(326.56, 71.65) controlPoint2: CGPointMake(326.55, 71.63)];
                [settingsButtonPath addCurveToPoint: CGPointMake(317.55, 65.55) controlPoint1: CGPointMake(322.89, 67.79) controlPoint2: CGPointMake(324.94, 68.65)];
                [settingsButtonPath addCurveToPoint: CGPointMake(320.85, 57.68) controlPoint1: CGPointMake(320.26, 59.08) controlPoint2: CGPointMake(319.61, 60.63)];
                [settingsButtonPath addCurveToPoint: CGPointMake(317.87, 50.39) controlPoint1: CGPointMake(320.33, 56.43) controlPoint2: CGPointMake(320.45, 56.73)];
                [settingsButtonPath addCurveToPoint: CGPointMake(325.15, 47.41) controlPoint1: CGPointMake(324.27, 47.77) controlPoint2: CGPointMake(322.52, 48.49)];
                [settingsButtonPath addCurveToPoint: CGPointMake(328.45, 39.55) controlPoint1: CGPointMake(326.2, 44.91) controlPoint2: CGPointMake(325.36, 46.93)];
                [settingsButtonPath addCurveToPoint: CGPointMake(336.32, 42.85) controlPoint1: CGPointMake(334.93, 42.26) controlPoint2: CGPointMake(333.38, 41.61)];
                [settingsButtonPath addCurveToPoint: CGPointMake(343.61, 39.86) controlPoint1: CGPointMake(337.57, 42.33) controlPoint2: CGPointMake(337.27, 42.45)];
                [settingsButtonPath addCurveToPoint: CGPointMake(346.59, 47.15) controlPoint1: CGPointMake(346.22, 46.25) controlPoint2: CGPointMake(346.08, 45.9)];
                [settingsButtonPath addCurveToPoint: CGPointMake(354.45, 50.45) controlPoint1: CGPointMake(349.11, 48.21) controlPoint2: CGPointMake(347.06, 47.35)];
                [settingsButtonPath addCurveToPoint: CGPointMake(351.15, 58.32) controlPoint1: CGPointMake(351.5, 57.48) controlPoint2: CGPointMake(352.29, 55.61)];
                [settingsButtonPath addCurveToPoint: CGPointMake(354.13, 65.61) controlPoint1: CGPointMake(351.67, 59.57) controlPoint2: CGPointMake(351.55, 59.27)];
                [settingsButtonPath addLineToPoint: CGPointMake(354.13, 65.61)];
                [settingsButtonPath closePath];
                [settingsButtonPath moveToPoint: CGPointMake(361, 47.78)];
                [settingsButtonPath addLineToPoint: CGPointMake(350.43, 43.34)];
                [settingsButtonPath addLineToPoint: CGPointMake(346.34, 33.34)];
                [settingsButtonPath addLineToPoint: CGPointMake(336.34, 37.43)];
                [settingsButtonPath addLineToPoint: CGPointMake(325.78, 33)];
                [settingsButtonPath addLineToPoint: CGPointMake(321.34, 43.57)];
                [settingsButtonPath addLineToPoint: CGPointMake(311.34, 47.66)];
                [settingsButtonPath addLineToPoint: CGPointMake(315.43, 57.66)];
                [settingsButtonPath addLineToPoint: CGPointMake(311, 68.22)];
                [settingsButtonPath addLineToPoint: CGPointMake(321.57, 72.66)];
                [settingsButtonPath addLineToPoint: CGPointMake(325.66, 82.66)];
                [settingsButtonPath addLineToPoint: CGPointMake(335.66, 78.57)];
                [settingsButtonPath addLineToPoint: CGPointMake(346.22, 83)];
                [settingsButtonPath addLineToPoint: CGPointMake(350.66, 72.43)];
                [settingsButtonPath addLineToPoint: CGPointMake(360.66, 68.34)];
                [settingsButtonPath addLineToPoint: CGPointMake(356.57, 58.34)];
                [settingsButtonPath addLineToPoint: CGPointMake(361, 47.78)];
                [settingsButtonPath closePath];
                settingsButtonPath.usesEvenOddFillRule = YES;
                [strokeColor2 setFill];
                [settingsButtonPath fill];
            }
        }
    }


    //// Page- 3
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, -301, 619);



        //// Group Начальный-экран 4
        {
        }



        CGContextRestoreGState(context);
    }


    //// Rectangle 2 Drawing
    UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(0, 618, 375, 49)];
    [color3 setFill];
    [rectangle2Path fill];


    //// FilterButton Drawing
    UIBezierPath* filterButtonPath = [UIBezierPath bezierPath];
    [filterButtonPath moveToPoint: CGPointMake(42.5, 55.5)];
    [filterButtonPath addLineToPoint: CGPointMake(62.5, 55.5)];
    [filterButtonPath addCurveToPoint: CGPointMake(65, 58) controlPoint1: CGPointMake(63.88, 55.5) controlPoint2: CGPointMake(65, 56.62)];
    [filterButtonPath addCurveToPoint: CGPointMake(62.5, 60.5) controlPoint1: CGPointMake(65, 59.38) controlPoint2: CGPointMake(63.88, 60.5)];
    [filterButtonPath addLineToPoint: CGPointMake(42.5, 60.5)];
    [filterButtonPath addCurveToPoint: CGPointMake(40, 58) controlPoint1: CGPointMake(41.12, 60.5) controlPoint2: CGPointMake(40, 59.38)];
    [filterButtonPath addCurveToPoint: CGPointMake(42.5, 55.5) controlPoint1: CGPointMake(40, 56.62) controlPoint2: CGPointMake(41.12, 55.5)];
    [filterButtonPath addLineToPoint: CGPointMake(42.5, 55.5)];
    [filterButtonPath closePath];
    [filterButtonPath moveToPoint: CGPointMake(42.5, 73)];
    [filterButtonPath addLineToPoint: CGPointMake(62.5, 73)];
    [filterButtonPath addCurveToPoint: CGPointMake(65, 75.5) controlPoint1: CGPointMake(63.88, 73) controlPoint2: CGPointMake(65, 74.12)];
    [filterButtonPath addCurveToPoint: CGPointMake(62.5, 78) controlPoint1: CGPointMake(65, 76.88) controlPoint2: CGPointMake(63.88, 78)];
    [filterButtonPath addLineToPoint: CGPointMake(42.5, 78)];
    [filterButtonPath addCurveToPoint: CGPointMake(40, 75.5) controlPoint1: CGPointMake(41.12, 78) controlPoint2: CGPointMake(40, 76.88)];
    [filterButtonPath addCurveToPoint: CGPointMake(42.5, 73) controlPoint1: CGPointMake(40, 74.12) controlPoint2: CGPointMake(41.12, 73)];
    [filterButtonPath addLineToPoint: CGPointMake(42.5, 73)];
    [filterButtonPath closePath];
    [filterButtonPath moveToPoint: CGPointMake(42.5, 38)];
    [filterButtonPath addLineToPoint: CGPointMake(62.5, 38)];
    [filterButtonPath addCurveToPoint: CGPointMake(65, 40.5) controlPoint1: CGPointMake(63.88, 38) controlPoint2: CGPointMake(65, 39.12)];
    [filterButtonPath addCurveToPoint: CGPointMake(62.5, 43) controlPoint1: CGPointMake(65, 41.88) controlPoint2: CGPointMake(63.88, 43)];
    [filterButtonPath addLineToPoint: CGPointMake(42.5, 43)];
    [filterButtonPath addCurveToPoint: CGPointMake(40, 40.5) controlPoint1: CGPointMake(41.12, 43) controlPoint2: CGPointMake(40, 41.88)];
    [filterButtonPath addCurveToPoint: CGPointMake(42.5, 38) controlPoint1: CGPointMake(40, 39.12) controlPoint2: CGPointMake(41.12, 38)];
    [filterButtonPath addLineToPoint: CGPointMake(42.5, 38)];
    [filterButtonPath closePath];
    [filterButtonPath moveToPoint: CGPointMake(35, 43)];
    [filterButtonPath addCurveToPoint: CGPointMake(40, 48) controlPoint1: CGPointMake(35, 45.76) controlPoint2: CGPointMake(37.24, 48)];
    [filterButtonPath addLineToPoint: CGPointMake(65, 48)];
    [filterButtonPath addCurveToPoint: CGPointMake(70, 43) controlPoint1: CGPointMake(67.76, 48) controlPoint2: CGPointMake(70, 45.76)];
    [filterButtonPath addLineToPoint: CGPointMake(70, 38)];
    [filterButtonPath addCurveToPoint: CGPointMake(65, 33) controlPoint1: CGPointMake(70, 35.24) controlPoint2: CGPointMake(67.76, 33)];
    [filterButtonPath addLineToPoint: CGPointMake(40, 33)];
    [filterButtonPath addCurveToPoint: CGPointMake(35, 38) controlPoint1: CGPointMake(37.24, 33) controlPoint2: CGPointMake(35, 35.24)];
    [filterButtonPath addLineToPoint: CGPointMake(25, 38)];
    [filterButtonPath addLineToPoint: CGPointMake(25, 33)];
    [filterButtonPath addLineToPoint: CGPointMake(20, 33)];
    [filterButtonPath addLineToPoint: CGPointMake(20, 73)];
    [filterButtonPath addCurveToPoint: CGPointMake(25, 78) controlPoint1: CGPointMake(20, 75.76) controlPoint2: CGPointMake(22.24, 78)];
    [filterButtonPath addLineToPoint: CGPointMake(25.55, 78)];
    [filterButtonPath addLineToPoint: CGPointMake(35, 78)];
    [filterButtonPath addCurveToPoint: CGPointMake(40, 83) controlPoint1: CGPointMake(35, 80.76) controlPoint2: CGPointMake(37.24, 83)];
    [filterButtonPath addLineToPoint: CGPointMake(65, 83)];
    [filterButtonPath addCurveToPoint: CGPointMake(70, 78) controlPoint1: CGPointMake(67.76, 83) controlPoint2: CGPointMake(70, 80.76)];
    [filterButtonPath addLineToPoint: CGPointMake(70, 73)];
    [filterButtonPath addCurveToPoint: CGPointMake(65, 68) controlPoint1: CGPointMake(70, 70.24) controlPoint2: CGPointMake(67.76, 68)];
    [filterButtonPath addLineToPoint: CGPointMake(40, 68)];
    [filterButtonPath addCurveToPoint: CGPointMake(35, 73) controlPoint1: CGPointMake(37.24, 68) controlPoint2: CGPointMake(35, 70.24)];
    [filterButtonPath addLineToPoint: CGPointMake(27.49, 73)];
    [filterButtonPath addCurveToPoint: CGPointMake(25, 70.51) controlPoint1: CGPointMake(26.11, 73) controlPoint2: CGPointMake(25, 71.88)];
    [filterButtonPath addLineToPoint: CGPointMake(25, 60.5)];
    [filterButtonPath addLineToPoint: CGPointMake(35, 60.5)];
    [filterButtonPath addCurveToPoint: CGPointMake(40, 65.5) controlPoint1: CGPointMake(35, 63.26) controlPoint2: CGPointMake(37.24, 65.5)];
    [filterButtonPath addLineToPoint: CGPointMake(65, 65.5)];
    [filterButtonPath addCurveToPoint: CGPointMake(70, 60.5) controlPoint1: CGPointMake(67.76, 65.5) controlPoint2: CGPointMake(70, 63.26)];
    [filterButtonPath addLineToPoint: CGPointMake(70, 55.5)];
    [filterButtonPath addCurveToPoint: CGPointMake(65, 50.5) controlPoint1: CGPointMake(70, 52.74) controlPoint2: CGPointMake(67.76, 50.5)];
    [filterButtonPath addLineToPoint: CGPointMake(40, 50.5)];
    [filterButtonPath addCurveToPoint: CGPointMake(35, 55.5) controlPoint1: CGPointMake(37.24, 50.5) controlPoint2: CGPointMake(35, 52.74)];
    [filterButtonPath addLineToPoint: CGPointMake(25, 55.5)];
    [filterButtonPath addLineToPoint: CGPointMake(25, 43)];
    [filterButtonPath addLineToPoint: CGPointMake(35, 43)];
    [filterButtonPath closePath];
    filterButtonPath.usesEvenOddFillRule = YES;
    [strokeColor2 setFill];
    [filterButtonPath fill];


    //// Cleanup
    CGGradientRelease(linearGradient);
    
    CGContextRestoreGState(context);

}

@end



CGRect StyleKitNameResizingBehaviorApply(StyleKitNameResizingBehavior behavior, CGRect rect, CGRect target)
{
    if (CGRectEqualToRect(rect, target) || CGRectEqualToRect(target, CGRectZero))
        return rect;

    CGSize scales = CGSizeZero;
    scales.width = ABS(target.size.width / rect.size.width);
    scales.height = ABS(target.size.height / rect.size.height);

    switch (behavior)
    {
        case StyleKitNameResizingBehaviorAspectFit:
        {
            scales.width = MIN(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case StyleKitNameResizingBehaviorAspectFill:
        {
            scales.width = MAX(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case StyleKitNameResizingBehaviorStretch:
            break;
        case StyleKitNameResizingBehaviorCenter:
        {
            scales.width = 1;
            scales.height = 1;
            break;
        }
    }

    CGRect result = CGRectStandardize(rect);
    result.size.width *= scales.width;
    result.size.height *= scales.height;
    result.origin.x = target.origin.x + (target.size.width - result.size.width) / 2;
    result.origin.y = target.origin.y + (target.size.height - result.size.height) / 2;
    return result;
}
